version: '2.1'
services:
  mongo:
    image: mongo:3.6.4
    ports:
      - 27017:27017
    command: --smallfiles

#  monitoring:
#    image: sngular/spring-boot-monitoring:latest
#    ports:
#      - 8080:8080
#    environment:
#      - "SPRING_PROFILES_ACTIVE=dev"

